use_frameworks!
inhibit_all_warnings!
platform :ios, '15.0'

# Please use 'pod install --repo-update' to ensure you have the latest versions of our SDKs.

target 'AppLovin MAX Demo App - Swift' do
  pod 'AppLovinSDK'
  pod 'AppLovinMediationIronSourceAdapter'
  pod 'AppLovinMediationFyberAdapter'
  pod 'AppLovinMediationFacebookAdapter'
  pod 'AppLovinMediationGoogleAdapter'
  pod 'AppLovinMediationInMobiAdapter'
  pod 'AppLovinMediationVungleAdapter'
  pod 'AppLovinMediationMintegralAdapter'
  pod 'AppLovinMediationByteDanceAdapter'
  pod 'AppLovinMediationUnityAdsAdapter'
  pod 'AppLovinMediationBidMachineAdapter'
  pod 'AppLovinMediationMolocoAdapter'
end
